name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./subscribe/pom.xml
          mvn clean package -f ./service/pom.xml
          mvn clean package -f ./subscribermanage/pom.xml
          mvn clean package -f ./subscribercenter/pom.xml

      - name: Docker Build and push for Subscribe
        uses: docker/build-push-action@v4
        with:
          context: ./subscribe
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscribe:latest
            ghcr.io/${{ github.repository }}/subscribe:${{ github.ref_name }}
            
      - name: Docker Build and push for Service
        uses: docker/build-push-action@v4
        with:
          context: ./service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/service:latest
            ghcr.io/${{ github.repository }}/service:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscribermanage
        uses: docker/build-push-action@v4
        with:
          context: ./subscribermanage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscribermanage:latest
            ghcr.io/${{ github.repository }}/subscribermanage:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscribercenter
        uses: docker/build-push-action@v4
        with:
          context: ./subscribercenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscribercenter:latest
            ghcr.io/${{ github.repository }}/subscribercenter:${{ github.ref_name }}
            
