---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribe
  labels:
    app: subscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribe
  template:
    metadata:
      labels:
        app: subscribe
    spec:
      containers:
        - name: subscribe
          image: username/subscribe:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: username/service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribermanage
  labels:
    app: subscribermanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribermanage
  template:
    metadata:
      labels:
        app: subscribermanage
    spec:
      containers:
        - name: subscribermanage
          image: username/subscribermanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribercenter
  labels:
    app: subscribercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribercenter
  template:
    metadata:
      labels:
        app: subscribercenter
    spec:
      containers:
        - name: subscribercenter
          image: username/subscribercenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: subscribe
  labels:
    app: subscribe
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribe


---


apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: service


---


apiVersion: v1
kind: Service
metadata:
  name: subscribermanage
  labels:
    app: subscribermanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribermanage


---


apiVersion: v1
kind: Service
metadata:
  name: subscribercenter
  labels:
    app: subscribercenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribercenter

